sudo: required
services:
  - docker

before_install:
  - docker build -t aws/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aws/docker-react npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-245634249045"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
